spring:
  application:
    name: prosperity-pilot-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prosperity_pilot_db?serverTimezone=America/Chicago&useSSL=false&allowPublicKeyRetrieval=true
    username: charleskriska
    password: demopassword123